# Add 'repo' label to any root file changes
repo:
- '*'

# Add '@domain/core' label to any change within the 'core' package
domain/core:
- package/core/*
- package/core/**/*

# Add 'test' label to any change to *.spec.js files within the source dir
docs:
- 'Documento - instrucciones/*'
- 'Documento - instrucciones/**/*'

# Add 'test' label to any change to *.spec.js files within the source dir
docword:
- 'Documento WORD/*'
- 'Documento WORD/**/*'


# Add 'test' label to any change to *.spec.js files within the source dir
code:
- 'C贸digo Fuente/*'
- 'C贸digo Fuente/**/*'

# Add 'test' label to any change to *.spec.js files within the source dir
script:
- 'Script de exploraci贸n/*'
- 'Script de exploraci贸n/**/*'


# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['src/**/*', '!src/docs/*']

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['src/**/*.js']
  all: ['!src/main.js']
#######################################

documentation:
- 'Documents/*'
- 'Documents/**/*'

backend:
- 'Server/*'
- 'Server/**/*'

frontend:
- 'Client/*'
- 'Client/**/*'

database:
- 'Data/*'
- 'Data/**/*'
